title: starting-with-typescript
tagline: A brand new course on Learning Lab
description: Starting with TypeScript
template:
  repo: starting-with-typescript-template
  name: starting-with-typescript-exercise
before:
  - type: createIssue
    title: Welcome to the TypeScript Exercise!
    body: new-issue.md
steps:
  - title: Install Git
    description: Learn how to install Git
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing Git
        body: install-git.md
  - title: Install NodeJS
    description: Learn how to install NodeJS
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing NodeJS
        body: install-nodejs.md
  - title: Install VS Code Insiders
    description: Learn how to install VS Code Insiders
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing VS Code Insiders
        body: install-vs-code-insiders.md
  - title: Install TypeScript
    description: Learn how to install TypeScript
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing TypeScript
        body: install-typescript.md
  - title: Support your teammates
    description: Learn which difficulties could arise on different operating systems and get used to tackle issues :)
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy taking a rest
        body: take-a-rest-and-support-others.md
  - title: Clone this repository and open the folder in Visual Code Insiders
    description: Learn how to git clone a repository and get started to develop in Visual Studio Code
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy Cloning
        body: git-clone-the-repository.md
  - title: Create an HTML File
    description: Learn how to create an HTML file which uses JavaScript Functions
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy HTML
        body: create-an-html-file.md
  - title: Create a TypeScript File with a function named doIt() which alerts hello world
    description: Learn how to create a TypeScript file
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy creating a TypeScript file
        body: create-a-typescript-file.md
  - title: Transpile the TypeScript File's content to JavaScript
    description: Learn how to transpile from TypeScript to JavaScript
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy transpiling
        body: transpile.md
  - title: Open the HTML File via a Browser
    description: Open the HTML file and play around with it
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Feel free to play around to get familiar with the stuff
        body: finish.md
