title: starting-with-typescript
tagline: A brand new course on Learning Lab
description: Starting with TypeScript
template:
  repo: starting-with-typescript-template
  name: starting-with-typescript-exercise
before:
  - type: createIssue
    title: Welcome to the show!
    body: new-issue.md
steps:
  - title: Play around with the generated html file
    description: Learn how to edit an html file
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createFile
        filename: my-html-file.html
        data:
          foo: bar
        message: creating my-html-file.html
    actions:
      - type: createIssue
        title: Enjoy Playing around with the html file
        body: play-with-html.md
  - title: Install Git
    description: Learn how to install Git
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing Git
        body: install-git.md
  - title: Install NodeJS
    description: Learn how to install NodeJS
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing NodeJS
        body: install-nodejs.md
  - title: Install VS Code Insiders
    description: Learn how to install VS Code Insiders
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing VS Code Insiders
        body: install-vs-code-insiders.md
  - title: Install TypeScript
    description: Learn how to install TypeScript
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing TypeScript
        body: install-typescript.md
  - title: Take a Rest and help others
    description: Learn how to take a rest and help others
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy taking a rest
        body: take-a-rest-and-support-others.md
  - title: Generate JS File by Transpiling TS File Content to JavaScript content
    description: Learn how to transpile to javascript and play around
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy transpiling to javascript and playing around
        body: generate-js-file-by-transpiling.md
      - type: createFile
        filename: greeter.ts
        message: creating greeter.ts
  - title: Grab Yourself a Cup of Coffee and Enjoy Life
    description: Learn how to enjoy life
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy Your Coffee
        body: coffee-time.md
