title: starting-with-typescript
tagline: A brand new course on Learning Lab
description: Starting with TypeScript
template:
  repo: starting-with-typescript-template
  name: starting-with-typescript-exercise
before:
  - type: createIssue
    title: Welcome to the TypeScript Exercise!
    body: new-issue.md
steps:
  - title: Install Git
    description: Learn how to install Git
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing Git
        body: install-git.md
  - title: Install NodeJS
    description: Learn how to install NodeJS
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing NodeJS
        body: install-nodejs.md
  - title: Install VS Code Insiders
    description: Learn how to install VS Code Insiders
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing VS Code Insiders
        body: install-vs-code-insiders.md
  - title: Install TypeScript
    description: Learn how to install TypeScript
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing TypeScript
        body: install-typescript.md
  - title: Support your teammates
    description: Learn which difficulties could arise on different operating systems and get used to tackle issues :)
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy taking a rest
        body: take-a-rest-and-support-others.md
  - title: Clone this repository and open the folder in Visual Code Insiders
    description: Learn how to git clone a repository and get started to develop in Visual Studio Code
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy Cloning
        body: git-clone-the-repository.md
  - title: Create a JavaScript file with a function named doIt() which alerts hello world
    description: Learn how to create a JavaScript file containing a function and calling it from your html file
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy creating a JavaScript file
        body: create-a-javascript-file.md
  - title: Generate JS File by Transpiling TS File Content to JavaScript content
    description: Learn how to transpile to javascript and play around
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy transpiling to javascript and playing around
        body: generate-js-file-by-transpiling.md
      - type: createFile
        filename: greeter.ts
        message: creating greeter.ts
  - title: Grab Yourself a Cup of Coffee and Enjoy Life
    description: Learn how to enjoy life
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy Your Coffee
        body: coffee-time.md
