title: starting-with-typescript
tagline: A brand new course on Learning Lab
description: Starting with TypeScript
template:
  repo: starting-with-typescript-template
  name: starting-with-typescript
before:
  - type: createIssue
    title: Welcome to the show!
    body: new-issue.md
steps:
  - title: Install Git
    description: Learn how to install git
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing git
        body: install-git.md
  - title: Install NodeJS
    description: Learn how to install NodeJS
    event: issues.closed
    link: "{{ repoUrl }}"
    actions:
      - type: createIssue
        title: Enjoy installing NodeJS
        body: install-nodejs.md
