title: starting-with-typescript
tagline: A brand new course on Learning Lab
description: Starting with TypeScript
template:
  repo: starting-with-typescript-template
  name: starting-with-typescript
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
